'use client'
import './globals.css'
import { usePathname } from 'next/navigation'
import { Inter } from 'next/font/google'
import Header from 'app/components/Header'
import { SessionProvider } from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Game Store',
  description: 'Generated by create next app',
}


export default function RootLayout({ children, session }) {
  const pathname = usePathname()
  if (pathname === '/auth/login' || pathname === '/auth/register') {
    console.log('login or register')
    return (
      <html lang="en">
        <body className='min-h-screen'>
          <main>{children}</main>
        </body>
      </html>
    )
  }

  return (
    <html lang="en" className='h-full'>
      <body className='h-full'>
        <SessionProvider session={session}>
          <Header />
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  )
  console.log('not login or register')
}
